"""Access Guardian agent definition.

Non-deterministic gatekeeper that decides whether the inbound request
may access Gmail / Drive / Calendar. The agent receives:

- ``instance``: Evolution instance name (e.g. ``Jennifer``).
- ``phone``: inbound phone digits.
- ``capability``: tool prefix (``gmail.*``, ``drive.*``, ``calendar.*``).

It returns a :class:`GuardianDecision` with one of three verdicts:

- ``allow`` — proceed to the manager specialist and tool call.
- ``request_oauth`` — user has not linked Google yet; reply with the
  OAuth link generated by the runtime.
- ``deny`` — caller is not the owner of the Evolution instance.

The decision is implemented by :func:`decide_guardian_deterministic`,
which is pure (no LLM) so it is fast, testable, and reproducible. The
graph node :func:`agent_orchestration.graph.guardian_node` calls this
function directly and stores the verdict on the graph state.
"""
from __future__ import annotations

import logging
from dataclasses import asdict, dataclass
from typing import Any, Dict, Iterable, Optional

from core.owner import OwnerResolution, resolve_owner
from core.oauth_per_user import get_user_oauth

logger = logging.getLogger(__name__)


ALLOWED_CAPABILITIES = {
    "gmail.read",
    "gmail.send",
    "drive.read",
    "drive.write",
    "calendar.read",
    "calendar.write",
    "knowledge.retrieve",
}

CAPABILITY_SCOPE_MAP = {
    "gmail.read": "https://www.googleapis.com/auth/gmail.readonly",
    "gmail.send": "https://www.googleapis.com/auth/gmail.send",
    "drive.read": "https://www.googleapis.com/auth/drive.readonly",
    "drive.write": "https://www.googleapis.com/auth/drive.file",
    "calendar.read": "https://www.googleapis.com/auth/calendar",
    "calendar.write": "https://www.googleapis.com/auth/calendar.events",
}


def normalize_capability(capability: str) -> str:
    if capability.startswith("calendar."):
        return "calendar.write" if capability in {
            "calendar.create_event", "calendar.update_event", "calendar.delete_event"
        } else "calendar.read"
    if capability.startswith("drive."):
        return "drive.write" if capability in {
            "drive.upload_file", "drive.create_folder"
        } else "drive.read"
    if capability.startswith("gmail."):
        return "gmail.send" if capability == "gmail.send_message" else "gmail.read"
    return capability


@dataclass
class GuardianDecision:
    verdict: str
    capability: str
    instance: str = ""
    phone: str = ""
    reason: str = ""
    oauth_link: str = ""
    granted_scopes: list = None
    user_email: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {k: v for k, v in asdict(self).items() if v not in (None, "")}


def _build_oauth_link(instance: str, phone: str) -> str:
    # GUARDRAIL (21/08/2026): em vez de expor a URL crua /oauth/google?phone=...
    # (que mostra o telefone no preview do WhatsApp e nao explica seguranca),
    # aponta para o mini-portal dedicado /a/{phone}/conectar com magic link
    # HMAC de curta validade. O portal explica a seguranca e oferece os botoes
    # "Conectar Google Workspace" + "Conectar Apps de Trabalho" (Composio).
    from core.magic_link import build_magic_link_url

    return build_magic_link_url(phone)


def _has_required_scope(granted: Iterable[str], required: str) -> bool:
    required_short = required.replace("https://www.googleapis.com/auth/", "")
    for scope in granted:
        scope_short = scope.replace("https://www.googleapis.com/auth/", "")
        if scope_short == required_short:
            return True
        if required_short in ("drive.file", "drive.readonly") and scope_short == "drive":
            return True
    return False


def decide_guardian(
    instance: str,
    phone: str,
    capability: str,
    *,
    resolution: Optional[OwnerResolution] = None,
    token_data: Optional[Dict[str, Any]] = None,
) -> GuardianDecision:
    cap = normalize_capability(capability)
    if cap not in ALLOWED_CAPABILITIES:
        return GuardianDecision(
            verdict="deny",
            capability=capability,
            instance=instance,
            phone=phone,
            reason=f"unknown_capability:{capability}",
        )

    if resolution is None and instance:
        resolution = resolve_owner(instance, fallback_phone=phone)
    if resolution is None:
        return GuardianDecision(
            verdict="deny",
            capability=capability,
            instance=instance,
            phone=phone,
            reason="instance_unresolved",
        )

    if cap == "knowledge.retrieve":
        return GuardianDecision(
            verdict="allow",
            capability=capability,
            instance=instance,
            phone=phone,
            reason="rag_no_oauth_required",
            granted_scopes=[],
        )

    if not token_data:
        token_data = get_user_oauth(phone) or {}

    granted = token_data.get("scopes") or []
    if not granted:
        from agent_loader import is_user_approved

        if not is_user_approved(phone):
            return GuardianDecision(
                verdict="unapproved_guest",
                capability=capability,
                instance=instance,
                phone=phone,
                reason="user_not_approved_by_admin",
            )
        return GuardianDecision(
            verdict="request_oauth",
            capability=capability,
            instance=instance,
            phone=phone,
            reason="oauth_missing",
            oauth_link=_build_oauth_link(instance, phone),
        )

    required_scope = CAPABILITY_SCOPE_MAP.get(cap)
    if required_scope and not _has_required_scope(granted, required_scope):
        return GuardianDecision(
            verdict="request_oauth",
            capability=capability,
            instance=instance,
            phone=phone,
            reason=f"scope_missing:{required_scope}",
            oauth_link=_build_oauth_link(instance, phone),
        )

    return GuardianDecision(
        verdict="allow",
        capability=capability,
        instance=instance,
        phone=phone,
        granted_scopes=list(granted),
        user_email=token_data.get("user_email", ""),
    )
